### ISSUE TITLE
Discovered A Bug

### ISSUE THREAD

**Issue by GuardHei** [tk-codes/uno#2]
If the play chooses the wild card but cancels when asked to pick the color, player then will be not able to choose other cards or draw.
Working to find the solution.
<img width="960" alt="qq20180203-114104 2x" src="https://user-images.githubusercontent.com/30316509/35762742-2a550e12-08d7-11e8-9934-960e57adef21.png">

**Comment by tk-codes** [comment]
@GuardHei Thank you very much for your report. Once you have found a solution, please make a pull request.

**Comment by tk-codes** [comment]
@GuardHei Issue is fixed now 🎉 
![uno-issue2](https://user-images.githubusercontent.com/3751899/107131742-7b414880-68d9-11eb-8e35-e5ef22cabb14.gif)
