### ISSUE TITLE
PC's draw Bug

### ISSUE THREAD

**Issue by ZyphonGT** [tk-codes/uno#4]
For example, PC currently has 4 cards

1. Player plays a card
2. PC cant play, so he draw ( In the LinkedList , cards amount = 5, but In the GUI it still shows only 4)

Because of this, if PC's newly drawn card can be played, the turn will be stuck on PC's turn ( Although, somehow purposely clicking player's card (which results in "Not your turn") somehow fixes the bug and PC plays his newly drawn card.

But if the newly drawn card isn't playable, then the GUI will always missing 1 card, until player clicks draw too, then suddenly PC's card finally shows the correct amount of cards

**Comment by tk-codes** [comment]
@ZyphonGT Thanks for the information. I guess it's a weird `repaint` issue with Java Swing.
PC mode is not supported in the rebuilt version anymore. In normal mode, the draw bug doesn't occur. Therefore I close this bug.
