### ISSUE TITLE
Violaciones de principios Solid - Interface Segregation

### ISSUE THREAD

**Issue by jazch08** [tk-codes/uno#6]
I: Principio de segregacion de Interfaces
1)	https://github.com/tk-codes/uno
 
![1](https://user-images.githubusercontent.com/63554935/99927318-f5b6ef00-2d12-11eb-8114-446a3ff028eb.png)

La interfaz UNOConstants viola el principio de Interface Segregation, algunas clases que implementan esta interfaz no utilizan todos los métodos, por lo tanto, se podría crear nuevas interfaces segregando esta.
Por ejemplo, la clase UNOCard implementa esa interfaz, sin embargo, no utiliza ninguna característica de la interfaz, sino más bien sus hijas son las que la implementan, sin embargo, nuevamente no todas implementan todas las características proporcionadas por la interfaz.
2)	https://github.com/tk-codes/uno
La interfaz GameConstants viola el principio de Interface Segregation, se podría crear nuevas interfaces separando los componentes de esta interfaz, ya que no se utilizan en su totalidad por todas las clases que implementan esta interfaz.
 
![2](https://user-images.githubusercontent.com/63554935/99927342-023b4780-2d13-11eb-89fd-359c49463305.png)

CORRECCIONES:
Se separo los componentes de UNOConstants y GameConstants y se creó dos nuevas interfaces UNOColors y UNOTypes. Para que las clases que antes implementaban las interfaces UNOConstants y GameConstants no estuvieran obligados a tener componentes que nunca iban a usar.
![3](https://user-images.githubusercontent.com/63554935/99927423-57775900-2d13-11eb-9c55-89b5ed0ce80f.png)
![4](https://user-images.githubusercontent.com/63554935/99927433-61995780-2d13-11eb-9881-a0ba22213091.png)
![5](https://user-images.githubusercontent.com/63554935/99927439-69f19280-2d13-11eb-8965-12dfaa266da8.png)
![6](https://user-images.githubusercontent.com/63554935/99927455-737afa80-2d13-11eb-8c03-a578412e197a.png)
![7](https://user-images.githubusercontent.com/63554935/99927464-7aa20880-2d13-11eb-9f66-59e60344c01b.png)

**Comment by tk-codes** [comment]
@jazch08 Thank you very much for reporting the issue in detail.
It is clearly very bad to use interfaces for constants. I didn't know solid principles 9 years ago when I started learning Java 🙈 .

Now I have completely rebuilt the core logic in DDD. Interfaces are not misused anymore :)
