### ISSUE TITLE
Use of Design Patterns

### ISSUE THREAD

**Issue by JavierVMC** [tk-codes/uno#7]
Hola, hemos revisado tu proyecto y recomendamos el uso del siguiente patron de diseño, adjunto un documento con las especificaciones para la implementación del patron de diseñoi en el codigo.
Docuento:
[Patron de diseño.docx](https://github.com/tk-codes/uno/files/5761049/Patron.de.diseno.docx)
Diagrama UML con el patron de diseño:
![uml](https://user-images.githubusercontent.com/72490838/103469346-6816e800-4d31-11eb-8d3a-8fd753a87128.png)

**Comment by tk-codes** [comment]
@JavierVMC 
Thanks for your suggestion. Could you please explain the benefits of using this iterator pattern?

**Comment by tk-codes** [comment]
@JavierVMC In version 2, it is implemented as round iterator. In addition, the playing direction can also reversed easily.
![image](https://user-images.githubusercontent.com/3751899/105638871-7b6f2c00-5e75-11eb-9db4-ae91b78757fd.png)

See https://github.com/tk-codes/uno/blob/uno-v2/src/main/java/domain/player/PlayerRoundIterator.java
